"""
Emit src/verbs/beats.ts from the read.

beats.ts claims every `at` and `dur` comes from the read rather than being
authored by hand. This is the thing that makes that true. What IS authored here
is the mapping from a spoken line to a treatment -- fx, chunks, emphasis --
because that is a direction decision, not a timing one.

  usage: python scripts/build-beats.py
"""

import io
import json

FPS = 60

# TYPE SCALE. Three steps mapped to rhetorical weight, because 28 of 29
# word-carrying beats used to render at the same 58px and the film had no
# hierarchy at all -- its only scale contrast came from four special treatments.
SM, MD, LG = 52, 76, 132

# POSITION LANGUAGE, as [x, y] px from frame centre.
#
# The long cut put 93% of its content in the middle third horizontally and 94%
# vertically -- sd 0.048 -- so for a whole minute nothing ever left the middle.
# Centre meant nothing because it was all there was.
#
# Now it means something. Act 1's list sits low and left and steps DOWN as it
# runs, so the burden literally presses on you; the hammer interrupts from dead
# centre; Act 2's answer lifts above the line; and the close returns to centre
# having earned it.
# Values are deliberately large. A first pass used [-72, 96] and moved the
# measured centre of mass by one percentage point -- on a 1280x720 frame that
# is a nudge, not a composition. These put the burden decisively in the lower
# left and lift the answer clear of the optical centre.
LOW_L = [-210, 148]
LOWER_L = [-210, 205]
LIFT = [0, -122]

# line index -> (fx, chunks on screen, extras)
# `chunks` is deliberately not `say`: the screen usually carries fewer words than
# the read, and several beats carry none because the animation is the line.
SPOKEN: dict[int, tuple] = {
    0:  ("s1-split", ["you started", "a", "Business"], {}),
    1:  ("arrow-point", ["Running you"], {"sizes": [MD], "pos": [-128, 84]}),
    2:  ("arrow-point", ["Answer it."], {"sizes": [MD], "pos": LOW_L, "cut": "hard"}),
    3:  ("arrow-point", ["Chase it."], {"sizes": [MD], "pos": LOWER_L, "cut": "hard"}),
    4:  ("hammer", ["Again."], {}),
    5:  ("arrow-point", ["Post it."], {"sizes": [MD], "pos": LOW_L, "cut": "hard"}),
    6:  ("arrow-point", ["Send it."], {"sizes": [MD], "pos": LOWER_L, "cut": "hard"}),
    7:  ("hammer", ["Again."], {}),
    8:  ("blackout", [], {}),
    9:  ("doesnt", ["Software doesn't run a business."], {"sizes": [SM], "pos": LIFT}),
    10: ("do-from-doesnt", ["People do."], {"sizes": [LG], "pos": LIFT}),
    # The tool is small and pushed aside; the operator owns the centre. The
    # contrast is staged, not just stated.
    11: ("tool-sweep", ["a", "tool"], {"sizes": [MD, MD], "pos": [-196, 62]}),
    # The emphasis line. accent is a chunk INDEX and 0 is falsy, which is why
    # treatments.tsx tests it with ===.
    12: ("build", ["an operator"], {"accent": 0, "sizes": [LG]}),
    # The human reveal gets the waterfall -- the one mechanic in the film that
    # reveals rather than fades.
    13: ("rise", ["A person."], {"sizes": [LG], "pos": LIFT}),
    14: ("conveyor", ["Answer"], {}),
    15: ("conveyor", ["Chase"], {}),
    16: ("conveyor", ["Book"], {}),
    17: ("hero-caps", ["ALL OF IT"], {}),
    18: ("conveyor", ["Your Name"], {}),
    19: ("rise", ["Nothing ships until a person says yes."], {"sizes": [SM], "pos": [0, 54]}),
    20: ("close-hop", [], {}),
    21: ("through", ["We operate it."], {}),
    22: ("close-morph", [], {}),
}

# Wordless beats, each filling a structural silence. `before` is the line whose
# gap it occupies; the animation is the line.
WORDLESS = [
    ("arrow-seed", 0),
]

HEAD = '''/**
 * THE TIMELINE — the single source of truth.
 *
 * Act boundaries, flips, hammer gearing and the close live here; camera.ts and
 * Verbs.tsx all derive from them. They used to hold their own hardcoded seconds
 * across five files, with the hammer offsets duplicated verbatim in two, so a
 * retime silently desynced the room flinch from the word.
 *
 * GENERATED by scripts/build-beats.py from scripts/vo-timing.json. Every `at`
 * and `dur` comes from the read itself: each line is generated on its own and
 * placed at a known offset, so the timeline is what was actually spoken rather
 * than a transcription of it. Edit the mapping in build-beats.py and re-run;
 * do not hand-edit the table below.
 *
 * `chunks` is what is ON SCREEN and `say` is what is SPOKEN. They are
 * deliberately different: the screen usually carries fewer words than the read,
 * and on several beats carries none at all because the animation is the line.
 */

export const FPS = 60;
export const W = 1280;
export const H = 720;
'''


def main() -> None:
    d = json.load(io.open("scripts/vo-timing.json", encoding="utf-8"))
    lines = {o["i"]: o for o in d["lines"]}
    total = d["total"]  # the read decides the film's length, not a constant

    beats = []
    for li, (fx, chunks, extra) in sorted(SPOKEN.items()):
        beats.append({
            "at": lines[li]["at"], "fx": fx, "chunks": chunks,
            "say": lines[li]["text"], "extra": extra,
            "vo": [lines[li]["at"], lines[li]["end"]],
        })

    for fx, before in WORDLESS:
        nxt = lines[before]["at"]
        prev = max((o["end"] for o in d["lines"] if o["end"] <= nxt), default=0.0)
        beats.append({"at": round(prev, 2), "fx": fx, "chunks": [],
                      "say": None, "extra": {}, "vo": None})

    beats.sort(key=lambda b: b["at"])
    beats.append({"at": round(lines[max(SPOKEN)]["end"], 2), "fx": "hold", "chunks": [],
                  "say": None, "extra": {}, "vo": None})
    beats.sort(key=lambda b: b["at"])

    for a, b in zip(beats, beats[1:]):
        a["dur"] = round(b["at"] - a["at"], 2)
    beats[-1]["dur"] = round(total - beats[-1]["at"], 2)

    def at_of(fx):
        return next(b["at"] for b in beats if b["fx"] == fx)

    # Flips land on act boundaries: out of the blackout, into the delivery run,
    # into the mascots. The film must END on Paper — the mark is an Ink tile.
    f0 = round(at_of("doesnt") - 0.20, 2)
    f1 = round(at_of("conveyor") - 0.10, 2)
    f2 = round(lines[19]["at"] - 0.20, 2)
    hammer = at_of("hammer")

    out = [HEAD]
    out.append(f"export const TOTAL = Math.round({total} * FPS);\n")
    out.append("\nexport const s = (n: number) => Math.round(n * FPS);\n")
    out.append(f'''
/**
 * Ink -> Paper -> Ink -> Paper. The first is delayed until after the blackout,
 * so the light arrives with the argument. The film must END on Paper: the mark
 * is an Ink tile and would vanish on an Ink ground.
 */
export const FLIPS = [{f0}, {f1}, {f2}];

/**
 * Hammer gearing, in frames from HAMMER_AT. ONE array — camera.ts and
 * treatments.tsx both import it. They used to declare their own, which is how
 * the room came to flinch on three beats while the word stamped on five.
 */
export const HAMMER_HITS = [0, 26, 46, 61, 72];
export const HAMMER_AT = {hammer};
''')
    out.append('''
export type Fx =
  | "arrow-seed" | "s1-split" | "arrow-point" | "hammer" | "calendar"
  | "blackout" | "doesnt" | "do-from-doesnt" | "tool-sweep" | "person"
  | "conveyor" | "hero-caps" | "up"
  | "mascot-appear" | "mascot-disarray" | "mascot-ordering" | "mascot-order"
  | "close-hop" | "close-morph" | "hold"
  | "build" | "through" | "dots" | "rise";

export type Phrase = {
  at: number;
  dur: number;
  fx: Fx;
  chunks: string[];
  say?: string;
  vo?: [number, number];
  accent?: number;
  mode?: "unit" | "group" | "read";
  sizes?: number[];
  /** [x, y] px from frame centre. Absent means centred. */
  pos?: [number, number];
  /**
   * "hard" ends the beat on a black frame instead of cross-fading into the
   * next. The graded reference cuts every card this way, with 1-8 frames of
   * ground between them, and adding those gaps was the single biggest scoring
   * change in that build. A list closing in on you should cut, not dissolve.
   */
  cut?: "hard";
};

export const PHRASES: Phrase[] = [
''')

    def js(v):
        return json.dumps(v).replace('"', '\\"') if isinstance(v, str) else json.dumps(v)

    for b in beats:
        row = f'  {{ at: {b["at"]}, dur: {b["dur"]}, fx: "{b["fx"]}", chunks: {json.dumps(b["chunks"])}'
        if b["say"]:
            esc = b["say"].replace('"', '\\"')
            row += f', say: "{esc}"'
        if b["vo"]:
            row += f', vo: [{b["vo"][0]}, {b["vo"][1]}]'
        for k, v in b["extra"].items():
            row += f", {k}: {json.dumps(v)}"
        out.append(row + " },\n")

    out.append("];\n")
    out.append("""
/**
 * Look a beat up by its treatment instead of re-typing its second.
 *
 * Every sequence component used to carry its own copy of the seconds it cared
 * about — Conveyor alone held fifteen — so a retime moved the words and left the
 * mechanism behind. Components ask the timeline for their own beats now.
 */
export const beatsOf = (fx: Fx) => PHRASES.filter((p) => p.fx === fx);
export const beatAt = (fx: Fx, n = 0) => beatsOf(fx)[n]?.at ?? 0;
export const beatEnd = (fx: Fx, n = 0) => {
  const b = beatsOf(fx)[n];
  return b ? b.at + b.dur : 0;
};
""")
    out.append(f'\nexport const CLOSE_AT = s({at_of("close-morph")});\n')

    io.open("src/verbs/beats.ts", "w", encoding="utf-8", newline="").write("".join(out))

    # The music build needs the blackout's cut and resume points and the film's
    # length. Emitting them here beats grepping numbers back out of TypeScript,
    # which is both fragile and a second place for them to be wrong.
    io.open("scripts/film.json", "w", encoding="utf-8").write(json.dumps({
        "total": total,
        "blackout": at_of("blackout"),
        "resume": f0,
        "flips": [f0, f1, f2],
        "close_at": at_of("close-morph"),
    }, indent=2))

    print(f"{len(beats)} beats, TOTAL {total}s")
    print(f"FLIPS  [{f0}, {f1}, {f2}]   HAMMER_AT {hammer}   CLOSE_AT {at_of('close-morph')}")
    print(f"\n{'at':>7} {'dur':>6}  fx")
    for b in beats:
        print(f"{b['at']:7.2f} {b['dur']:6.2f}  {b['fx']:16s} {b['say'] or ''}")


if __name__ == "__main__":
    main()
